### ISSUE TITLE
Skip project pipeline job that customizes un-existing job

### ISSUE THREAD

**Issue by morucci** [softwarefactory-project/zuul-weeder#2]
This job [1] is added in the graph and displayed by the WUI. 
However notice that it has no relationship with other config element. Indead tox-python37 does not exist.

Zuul reports a config error for that tenant:
```
    fedora-infra/fmn - .zuul.yaml (develop)

    Zuul encountered a syntax error while parsing its configuration in the
    repo fedora-infra/fmn on branch develop.  The error was:

      Job tox-python37 not defined

    The error appears in the following project stanza:

      project:
          check:
            jobs:
              - tox-lint:
                  override-checkout: master
                  vars:
                    dependencies:
                      - libpq-devel
                      - krb5-devel
              - tox-python37:
                  override-checkout: master
                  vars:
                    dependencies:
                      - libpq-devel
                      - krb5-devel
              - tox-python38:
                  override-checkout: master
                  vars:
                    dependencies:
                      - libpq-devel
                      - krb5-devel
              - tox-python39:
                  override-checkout: master
                  vars:
                    dependencies:
                      - libpq-devel
                      - krb5-devel
              - simple-tox-docs:
                  override-checkout: master
                  vars:
                    dependencies:
                      - libpq-devel
                      - krb5-devel
                      - python3-pydot
              - tox-diff-cover:
                  override-checkout: master
                  vars:
                    dependencies:
                      - libpq-devel
                      - krb5-devel

      in "fedora-infra/fmn/.zuul.yaml@develop", line 1, column 3
```

Perhaps we should skip the project pipeline job if the customized job is missing ?

[1] https://softwarefactory-project.io/weeder/tenant/fedora/object/job/tox-python37
